//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingELF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartTable
    {
        public int CartID { get; set; }
        public int UserID { get; set; }
        public int PID { get; set; }
    
        public virtual SizeTable SizeTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
