//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingELF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerDetailsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellerDetailsTable()
        {
            this.SellerTable1 = new HashSet<SellerTable>();
        }
    
        public int SellerDetailID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string pincode { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string AccountHolderName { get; set; }
        public string accountNumber { get; set; }
        public string IFSCCode { get; set; }
        public string accountType { get; set; }
        public int ShippingFee { get; set; }
        public string GSTNumber { get; set; }
        public string PANCardNumber { get; set; }
        public Nullable<int> SellerID { get; set; }
    
        public virtual SellerTable SellerTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerTable> SellerTable1 { get; set; }
    }
}
