//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingELF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoppingELFEntities : DbContext
    {
        public ShoppingELFEntities()
            : base("name=ShoppingELFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressTable> AddressTable { get; set; }
        public virtual DbSet<CartTable> CartTable { get; set; }
        public virtual DbSet<CategoryTable> CategoryTable { get; set; }
        public virtual DbSet<OrderTable> OrderTable { get; set; }
        public virtual DbSet<ProductTable> ProductTable { get; set; }
        public virtual DbSet<SellerDetailsTable> SellerDetailsTable { get; set; }
        public virtual DbSet<SellerTable> SellerTable { get; set; }
        public virtual DbSet<SizeTable> SizeTable { get; set; }
        public virtual DbSet<SoldTable> SoldTable { get; set; }
        public virtual DbSet<SubCategoryTable> SubCategoryTable { get; set; }
        public virtual DbSet<SuitableForTable> SuitableForTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
