//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingELF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizeTable
    {
        public int PID { get; set; }
        public string productSize { get; set; }
        public int productQuantity { get; set; }
        public int ProductID { get; set; }
        public int productPrice { get; set; }
    
        public virtual ProductTable ProductTable { get; set; }
    }
}
