//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingELF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldTable
    {
        public int SoldID { get; set; }
        public int SellerID { get; set; }
        public string productName { get; set; }
        public string productBrand { get; set; }
        public int productPrice { get; set; }
        public int productQuantity { get; set; }
        public string productSize { get; set; }
        public string productPicture { get; set; }
        public string UserName { get; set; }
        public int PID { get; set; }
    
        public virtual SellerTable SellerTable { get; set; }
        public virtual SizeTable SizeTable { get; set; }
    }
}
